### ISSUE TITLE
Not a wise idea for adding a postgreDB as an intermediary data processing method

### ISSUE THREAD

**Issue by kxdkxd** [manganese/zcash-empirical-analysis#3]
Why not directly process block data to csv directly from zcash rpc?

**Comment by Haaroon** [comment]
the truth mate, i just needed something super easy to manage during my research, yes your right you can move straight to CSV. But the issue I found was, if theres a rare block-reorg you have to remake the large CSV Files. CSV files started to become unmanageable. So postgres was much easier.
